test_task:
  matrix:
    - container:
        image: rust:latest
    - container:
        image: rustlang/rust:nightly
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  env:
    matrix:
      - OA_FRONTEND: actix-frontend
      - OA_FRONTEND: iron-frontend
      - OA_FRONTEND: rouille-frontend
  build_script: cargo build --no-default-features --features "$OA_FRONTEND"
  test_script: cargo test --no-default-features --features "$OA_FRONTEND"
  before_cache_script: rm -rf $CARGO_HOME/registry/index

nightly_task:
  container:
    image: rustlang/rust:nightly
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  build_script: cargo build --no-default-features --features "rocket-frontend"
  test_script: cargo test --no-default-features --features "rocket-frontend"
  before_cache_script: rm -rf $CARGO_HOME/registry/index

doc_task:
  container:
    image: rustlang/rust:nightly
  script: cargo doc --no-deps --document-private-items --all-features
