[package]
name = "oxide-auth"
version = "0.3.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
repository = "https://github.com/HeroicKatora/oxide-auth.git"

description = "A OAuth2 server library, for use in combination with iron or other frontends, featuring a set of configurable and pluggable backends."
readme = "Readme.md"

keywords = ["oauth", "server", "oauth2"]
categories = ["web-programming::http-server", "authentication"]
license = "MIT"


[dependencies]
base64 = "^0.9"
chrono = "^0.4"
futures = { version = "0.1.18", optional = true }
gotham = { version = "^0.2", optional = true }
gotham_derive = { version = "^0.2", optional = true }
hyper = { version = "^0.11", optional = true }
mime = { version = "^0.3", optional = true }
iron = { version = "^0.6", optional = true }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
serde_urlencoded = { version = "0.5.1", optional = true }
rand = "^0.4"
ring = "0.13.0-alpha"
rouille = { version = "^2.0", optional = true }
rmp-serde = "^0.13"
url = "^1.6"
urlencoded = { version = "^0.6", optional = true }
lazy_static = { version = "1.0", optional = true }

[features]
default = ["gotham-frontend", "iron-frontend", "rouille-frontend"]
iron-frontend = ["iron", "urlencoded"]
rouille-frontend = ["rouille", "serde_urlencoded"]
gotham-frontend = ["gotham", "gotham_derive", "hyper", "mime", "futures", "lazy_static"]

[dev-dependencies]
router = "^0.6"
reqwest = "^0.8"
