[package]
name = "oxide_auth"
version = "0.1.0-0-noncompliant"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]

description = "A OAuth2 server library, for use in combination with iron or other frontends, featuring a set of configurable and pluggable backends."
readme = "Readme.md"

keywords = ["oauth", "server", "oauth2"]
categories = ["web-programming::http-server", "authentication"]
license = "MIT"


[dependencies]
chrono = "^0.4"
rand = "^0.3"
base64 = "^0.6"
url = "^1.5"
ring = "^0.12"
iron = { version = "^0.5", optional = true }
urlencoded = { version = "^0.5", optional = true }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
rmp-serde = "^0.13"

[features]
default = ["iron-backend"]
iron-backend = ["iron", "urlencoded"]

[dev-dependencies]
router = "^0.5"
reqwest = "^0.8"
