[package]
name = "oauth2-server"
version = "0.1.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]

[dependencies]
chrono = "0.4"
rand = "0.3"
base64 = "~0.6.0"
url = "*"
ring = "*"
iron = { version = "*", optional = true }
urlencoded = { version = "*", optional = true }

[features]
default = ["iron-backend"]
iron-backend = ["iron", "urlencoded"]

[dev-dependencies]
router = "*"
reqwest = "*"
