[package]
name = "oxide-auth"
version = "0.2.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
repository = "https://github.com/HeroicKatora/oxide-auth.git"

description = "A OAuth2 server library, for use in combination with iron or other frontends, featuring a set of configurable and pluggable backends."
readme = "Readme.md"

keywords = ["oauth", "server", "oauth2"]
categories = ["web-programming::http-server", "authentication"]
license = "MIT"


[dependencies]
base64 = "^0.9"
chrono = "^0.4"
iron = { version = "^0.5", optional = true }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
rand = "^0.4"
ring = "0.13.0-alpha"
rmp-serde = "^0.13"
url = "^1.6"
urlencoded = { version = "^0.5", optional = true }

[features]
default = ["iron-backend"]
iron-backend = ["iron", "urlencoded"]

[dev-dependencies]
router = "^0.5"
reqwest = "^0.8"
