[package]
name = "oxide-auth"
version = "0.3.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
repository = "https://github.com/HeroicKatora/oxide-auth.git"

description = "A OAuth2 server library, for use in combination with iron or other frontends, featuring a set of configurable and pluggable backends."
readme = "Readme.md"

keywords = ["oauth", "server", "oauth2"]
categories = ["web-programming::http-server", "authentication"]
license = "MIT"


[dependencies]
actix = { version = "0.5.5", optional = true }
actix-web = { version = "^0.6.0", optional = true }
base64 = "^0.9"
chrono = "^0.4"
iron = { version = "^0.6", optional = true }
futures = { version = "^0.1", optional = true }
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
serde_urlencoded = { version = "0.5.1", optional = true }
rand = "^0.4"
ring = "^0.12"
router = { version = "^0.6", optional = true }  # Only for iron example
rouille = { version = "^2.0", optional = true }
rmp-serde = "^0.13"
url = "^1.6"
urlencoded = { version = "^0.6", optional = true }

[features]
default = ["actix-frontend"]
actix-frontend = ["actix", "actix-web", "futures"]
iron-frontend = ["iron", "urlencoded",]
rouille-frontend = ["rouille", "serde_urlencoded"]

iron-example = ["router"]

[dev-dependencies]
reqwest = "^0.8"

[[example]]
name = "authorization_code"
required-features = ["iron-frontend", "iron-example"]

[[example]]
name = "authorization_actix"
required-features = ["actix-frontend"]

[[example]]
name = "authorization_rouille"
required-features = ["rouille-frontend"]
