[package]
name = "oxide-auth-iron"
version = "0.0.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
repository = "https://github.com/HeroicKatora/oxide-auth.git"

description = "A OAuth2 server library, for actix, gotham or other libraries, featuring a set of configurable and pluggable backends."

keywords = ["oauth", "server", "oauth2"]
categories = ["web-programming::http-server", "authentication"]
license = "MIT"

[lib]
path = "iron.rs"

[dependencies]
iron = "0.6"
oxide-auth = { path = "../oxide-auth" }
router = "0.6"
serde_urlencoded = "0.5.1"
